export const lang = {
  en: {
    search: "search",
    gptSearchPlaceholder: "Not Sure What to Watch? Start Here. . .",
    logout: "Logout",
    gptSearchBtnPlaceholder: "Explore with GPT",
    navHomeBtn: "Home",
    navTvShowBtn: "TV Shows",
    navMoviesBtn: "Movies",
    navNewAndPopularBtn: "New & Popular",
    navMyListBtn: "My List",
    playBtn: "Play",
    moreInfoBtn: "More Info",
    trending: "Trending",
    nowPlaying: "Now Playing",
    popular: "Popular",
    topRated: "Top Rated",
    upcoming: "Upcoming",
    profileSettings: "Profile Settings",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceholder: "निश्चित नहीं कि क्या देखना है? यहाँ से शुरू। . . .",
    logout: "लॉग आउट",
    gptSearchBtnPlaceholder: "GPT के साथ अन्वेषण करें",
    navHomeBtn: "होम",
    navTvShowBtn: "टीवी शो",
    navMoviesBtn: "फिल्में",
    navNewAndPopularBtn: "नया और लोकप्रिय",
    navMyListBtn: "मेरी सूची",
    playBtn: "चलाएं",
    moreInfoBtn: "अधिक जानकारी",
    trending: "प्रचलित",
    nowPlaying: "अब चल रही हैं",
    popular: "लोकप्रिय",
    topRated: "सर्वोच्च रेटेड",
    upcoming: "आगामी",
    profileSettings: "प्रोफ़ाइल सेटिंग्स",
  },
  marathi: {
    search: "शोध",
    gptSearchPlaceholder: "काय पहावे याची खात्री नाही? येथे प्रारंभ करा. . .",
    logout: "लॉगआउट करा",
    gptSearchBtnPlaceholder: "GPT सह एक्सप्लोर करा",
    navHomeBtn: "होम",
    navTvShowBtn: "टीव्ही शो",
    navMoviesBtn: "चित्रपट",
    navNewAndPopularBtn: "नवीन आणि लोकप्रिय",
    navMyListBtn: "माझी यादी",
    playBtn: "प्ले",
    moreInfoBtn: "अधिक माहिती",
    trending: "ट्रेंडिंग",
    nowPlaying: "आता प्ले होत आहे",
    popular: "लोकप्रिय",
    topRated: "उच्च रेट केलेले",
    upcoming: "उपलब्ध होणार",
    profileSettings: "प्रोफाइल सेटिंग्ज",
  },
};
