export const lang = {
  en: {
    search: "search",
    gptSearchPlaceholder: "Not Sure What to Watch? Start Here. . .",
    logout: "Logout",
    gptSearchBtnPlaceholder: "Explore with GPT",
    navHomeBtn: "Home",
    navTvShowBtn: "TV Shows",
    navMoviesBtn: "Movies",
    navNewAndPopularBtn: "New & Popular",
    navMyListBtn: "My List",
    playBtn: "Play",
    moreInfoBtn: "More Info",
    trending: "Trending",
    nowPlaying: "Now Playing",
    popular: "Popular",
    topRated: "Top Rated",
    upcoming: "Upcoming",
    profileSettings: "Profile Settings",
    welcome: "Welcome to Netflix GPT Search",
    try_searching: "Try searching for:",
    comedy_example: "Comedy Movies like 'The Office'",
    bollywood_romantic_example: "Bollywood Romantic Movies",
    thriller_example: "Thriller Movies from Hollywood",
    scifi_example: "Sci-fi Movies like 'Inception'",
    nolan_movies_example: "Movies by Christopher Nolan",
    prompt: "Type in the search bar to get recommendations",
    genres_example:
      "Specify genres, countries, or themes like 'Korean Dramas' or 'Action Movies from the 90s.'",
    discover_recommendations:
      "Discover movie recommendations based on your interests!",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceholder: "निश्चित नहीं कि क्या देखना है? यहाँ से शुरू। . . .",
    logout: "लॉग आउट",
    gptSearchBtnPlaceholder: "GPT के साथ अन्वेषण करें",
    navHomeBtn: "होम",
    navTvShowBtn: "टीवी शो",
    navMoviesBtn: "फिल्में",
    navNewAndPopularBtn: "नया और लोकप्रिय",
    navMyListBtn: "मेरी सूची",
    playBtn: "चलाएं",
    moreInfoBtn: "अधिक जानकारी",
    trending: "प्रचलित",
    nowPlaying: "अब चल रही हैं",
    popular: "लोकप्रिय",
    topRated: "सर्वोच्च रेटेड",
    upcoming: "आगामी",
    profileSettings: "प्रोफ़ाइल सेटिंग्स",
    welcome: "नेटफ्लिक्स GPT खोज में आपका स्वागत है",
    try_searching: "कोशिश करें खोजने की:",
    comedy_example: "'द ऑफिस' जैसी कॉमेडी फिल्में",
    bollywood_romantic_example: "बॉलीवुड रोमांटिक फिल्में",
    thriller_example: "हॉलीवुड से थ्रिलर फिल्में",
    scifi_example: "'इंसेप्शन' जैसी साइंस-फिक्शन फिल्में",
    nolan_movies_example: "क्रिस्टोफर नोलन की फिल्में",
    prompt: "सुझाव पाने के लिए सर्च बार में टाइप करें",
    genres_example:
      "शैली, देश, या थीम के साथ खोजें जैसे 'कोरियन ड्रामा' या '90 के दशक की एक्शन फिल्में'",
    discover_recommendations: "अपने रुचियों के आधार पर फिल्म अनुशंसाएँ खोजें!",
  },
  marathi: {
    search: "शोध",
    gptSearchPlaceholder: "काय पहावे याची खात्री नाही? येथे प्रारंभ करा. . .",
    logout: "लॉगआउट करा",
    gptSearchBtnPlaceholder: "GPT सह एक्सप्लोर करा",
    navHomeBtn: "होम",
    navTvShowBtn: "टीव्ही शो",
    navMoviesBtn: "चित्रपट",
    navNewAndPopularBtn: "नवीन आणि लोकप्रिय",
    navMyListBtn: "माझी यादी",
    playBtn: "प्ले",
    moreInfoBtn: "अधिक माहिती",
    trending: "ट्रेंडिंग",
    nowPlaying: "आता प्ले होत आहे",
    popular: "लोकप्रिय",
    topRated: "उच्च रेट केलेले",
    upcoming: "उपलब्ध होणार",
    profileSettings: "प्रोफाइल सेटिंग्ज",
    welcome: "नेटफ्लिक्स GPT शोधात आपले स्वागत आहे",
    try_searching: "शोधण्याचा प्रयत्न करा:",
    comedy_example: "'द ऑफिस' सारख्या कॉमेडी चित्रपट",
    bollywood_romantic_example: "बॉलीवूड रोमँटिक चित्रपट",
    thriller_example: "हॉलिवूड थ्रिलर चित्रपट",
    scifi_example: "'इंसेप्शन' सारख्या विज्ञान-कथा चित्रपट",
    nolan_movies_example: "क्रिस्टोफर नोलन यांचे चित्रपट",
    prompt: "शिफारसी मिळवण्यासाठी शोध बारमध्ये टाइप करा",
    genres_example:
      "शैली, देश किंवा थीमचे तपशील द्या जसे 'कोरियन ड्रामा' किंवा '90 च्या दशकातील ॲक्शन चित्रपट'",
    discover_recommendations:
      "तुमच्या आवडींवर आधारित चित्रपटांच्या शिफारसी शोधा!",
  },
  tamil: {
    search: "தேடு",
    gptSearchPlaceholder:
      "என்ன பார்க்க வேண்டும் என தெரியவில்லை? இங்கு தொடங்கவும்...",
    logout: "வெளியேறு",
    gptSearchBtnPlaceholder: "GPT மூலம் ஆராயுங்கள்",
    navHomeBtn: "முகப்பு",
    navTvShowBtn: "டிவி ஷோ",
    navMoviesBtn: "திரைப்படங்கள்",
    navNewAndPopularBtn: "புதிய மற்றும் பிரபலமான",
    navMyListBtn: "என் பட்டியல்",
    playBtn: "ஒலியுங்கள்",
    moreInfoBtn: "மேலும் தகவல்",
    trending: "பிரபலமானது",
    nowPlaying: "இப்போது ஒலிக்கிறது",
    popular: "பிரபலமான",
    topRated: "உயர் மதிப்பீடு",
    upcoming: "வந்துவிடுகிறது",
    profileSettings: "சுயவிவரம் அமைப்புகள்",
    welcome: "நெட்‌ஃபிளிக்ஸ் GPT தேடலுக்கு வரவேற்கிறோம்",
    try_searching: "தேடவும்:",
    comedy_example: "'தி ஆபிஸ்' போன்ற காமெடி திரைப்படங்கள்",
    bollywood_romantic_example: "பொல்லிவுட் காதல் திரைப்படங்கள்",
    thriller_example: "ஹாலிவுட் திரில்லர் திரைப்படங்கள்",
    scifi_example: "'இன்செப்ஷன்' போன்ற சயின்ஸ்-ஃபிக்ஷன் திரைப்படங்கள்",
    nolan_movies_example: "கிரிஸ்டோபர் நோலன் திரைப்படங்கள்",
    prompt: "முடிவுகள் பெற தேடும் இடத்தில் பதிவேற்றவும்",
    genres_example:
      "குறிப்பிடுங்கள்: 'கொரிய டிராமாக்கள்' அல்லது '90களின் ஆக்சன் திரைப்படங்கள்' போன்று வகைகள், நாடுகள், அல்லது தலைப்புகள்",
    discover_recommendations:
      "உங்கள் விருப்பங்களுக்கு அடிப்படையில் திரைப்பட சிபாரிசுகளை கண்டறிக!",
  },
  telugu: {
    search: "సోండించు",
    gptSearchPlaceholder: "ఏది చూడాలో తెలుసుకోవడం లేదు? ఇక్కడ ప్రారంభించండి...",
    logout: "లాగ్ అవుట్",
    gptSearchBtnPlaceholder: "GPT తో అన్వేషించండి",
    navHomeBtn: "హోమ్",
    navTvShowBtn: "టీవీ షోలు",
    navMoviesBtn: "చిత్రాలు",
    navNewAndPopularBtn: "కొత్త మరియు ప్రజాదరణ పొందిన",
    navMyListBtn: "నా జాబితా",
    playBtn: "ప్లే",
    moreInfoBtn: "ఇంకా సమాచారం",
    trending: "ట్రెండింగ్",
    nowPlaying: "ప్రస్తుతం ప్రదర్శిస్తున్నారు",
    popular: "ప్రజాదరణ పొందిన",
    topRated: "ఉన్నత రేటింగ్",
    upcoming: "రాబోయే",
    profileSettings: "ప్రొఫైల్ సెట్టింగ్స్",
    welcome: "నెట్‌ఫ్లిక్స్ GPT శోధనకు స్వాగతం",
    try_searching: "శోధించడానికి ప్రయత్నించండి:",
    comedy_example: "'ది ఆఫీస్' వంటి కామెడీ చిత్రాలు",
    bollywood_romantic_example: "బాలీవుడ్ రొమాంటిక్ చిత్రాలు",
    thriller_example: "హాలీవుడ్ థ్రిల్లర్ చిత్రాలు",
    scifi_example: "'ఇన్‌సెప్షన్' వంటి సైన్స్-ఫిక్షన్ చిత్రాలు",
    nolan_movies_example: "క్రిస్టోఫర్ నోలన్ చిత్రాలు",
    prompt: "సిఫార్సులు పొందడానికి శోధన క్రమంలో టైప్ చేయండి",
    genres_example:
      "శ్రేణులు, దేశాలు లేదా 'కొరియన్ డ్రామాలు' లేదా '90ల యాక్షన్ సినిమాలు' వంటి అంశాలను నిర్దేశించండి.",
    discover_recommendations:
      "మీ అభిరుచుల ఆధారంగా సినిమాల సిఫారసులను కనుగొనండి!",
  },
  spanish: {
    search: "Buscar",
    gptSearchPlaceholder: "¿No estás seguro de qué ver? Comienza aquí...",
    logout: "Cerrar sesión",
    gptSearchBtnPlaceholder: "Explora con GPT",
    navHomeBtn: "Inicio",
    navTvShowBtn: "Series",
    navMoviesBtn: "Películas",
    navNewAndPopularBtn: "Nuevas y populares",
    navMyListBtn: "Mi lista",
    playBtn: "Reproducir",
    moreInfoBtn: "Más información",
    trending: "Tendencias",
    nowPlaying: "Ahora en reproducción",
    popular: "Popular",
    topRated: "Mejor valoradas",
    upcoming: "Próximamente",
    profileSettings: "Configuración del perfil",
    welcome: "Bienvenido a la búsqueda de Netflix GPT",
    try_searching: "Intenta buscar:",
    comedy_example: "Películas de comedia como 'The Office'",
    bollywood_romantic_example: "Películas románticas de Bollywood",
    thriller_example: "Películas de thriller de Hollywood",
    scifi_example: "Películas de ciencia ficción como 'Inception'",
    nolan_movies_example: "Películas de Christopher Nolan",
    prompt: "Escribe en la barra de búsqueda para obtener recomendaciones",
    genres_example:
      "Especifica géneros, países o temas como 'Dramas coreanos' o 'Películas de acción de los 90.'",
    discover_recommendations:
      "¡Descubre recomendaciones de películas basadas en tus intereses!",
  },
  korean: {
    search: "검색",
    gptSearchPlaceholder: "무엇을 볼지 모르겠나요? 여기서 시작하세요...",
    logout: "로그아웃",
    gptSearchBtnPlaceholder: "GPT와 탐색하기",
    navHomeBtn: "홈",
    navTvShowBtn: "TV 프로그램",
    navMoviesBtn: "영화",
    navNewAndPopularBtn: "새로운 및 인기",
    navMyListBtn: "내 목록",
    playBtn: "재생",
    moreInfoBtn: "자세히 보기",
    trending: "트렌드",
    nowPlaying: "현재 재생 중",
    popular: "인기",
    topRated: "최고 평점",
    upcoming: "곧 출시 예정",
    profileSettings: "프로필 설정",
    welcome: "넷플릭스 GPT 검색에 오신 것을 환영합니다",
    try_searching: "검색해 보세요:",
    comedy_example: "'더 오피스'와 같은 코미디 영화",
    bollywood_romantic_example: "볼리우드 로맨틱 영화",
    thriller_example: "헐리우드 스릴러 영화",
    scifi_example: "'인셉션'과 같은 SF 영화",
    nolan_movies_example: "크리스토퍼 놀란의 영화",
    prompt: "추천을 받으려면 검색창에 입력하세요",
    genres_example:
      "장르, 국가 또는 '한국 드라마' 또는 '90년대 액션 영화'와 같은 주제를 지정하세요.",
    discover_recommendations: "관심사에 따라 영화 추천을 찾아보세요!",
  },
  japanese: {
    search: "検索",
    gptSearchPlaceholder:
      "何を見るか決まっていませんか？ここから始めましょう...",
    logout: "ログアウト",
    gptSearchBtnPlaceholder: "GPTで探す",
    navHomeBtn: "ホーム",
    navTvShowBtn: "テレビ番組",
    navMoviesBtn: "映画",
    navNewAndPopularBtn: "新着・人気",
    navMyListBtn: "マイリスト",
    playBtn: "再生",
    moreInfoBtn: "詳細情報",
    trending: "トレンド",
    nowPlaying: "現在再生中",
    popular: "人気",
    topRated: "高評価",
    upcoming: "近日公開",
    profileSettings: "プロフィール設定",
    welcome: "Netflix GPT検索へようこそ",
    try_searching: "検索してみてください:",
    comedy_example: "'ザ・オフィス'のようなコメディ映画",
    bollywood_romantic_example: "ボリウッドのロマンティック映画",
    thriller_example: "ハリウッドのスリラー映画",
    scifi_example: "'インセプション'のようなSF映画",
    nolan_movies_example: "クリストファー・ノーランの映画",
    prompt: "おすすめを得るために検索バーに入力してください",
    genres_example:
      "ジャンル、国、または '韓国ドラマ' や '90年代のアクション映画' などのテーマを指定してください。",
    discover_recommendations:
      "あなたの興味に基づいて映画のおすすめを発見しましょう！",
  },
};
