export const lang = {
  en: {
    search: "search",
    gptSearchPlaceholder: "Not Sure What to Watch? Start Here. . .",
    logout: "Logout",
    gptSearchBtnPlaceholder: "Explore with GPT",
    navHomeBtn: "Home",
    navTvShowBtn: "TV Shows",
    navMoviesBtn: "Movies",
    navNewAndPopularBtn: "New & Popular",
    navMyListBtn: "My List",
    playBtn: "Play",
    moreInfoBtn: "More Info",
    trending: "Trending",
    nowPlaying: "Now Playing",
    popular: "Popular",
    topRated: "Top Rated",
    upcoming: "Upcoming",
    profileSettings: "Profile Settings",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceholder: "निश्चित नहीं कि क्या देखना है? यहाँ से शुरू। . . .",
    logout: "लॉग आउट",
    gptSearchBtnPlaceholder: "GPT के साथ अन्वेषण करें",
    navHomeBtn: "होम",
    navTvShowBtn: "टीवी शो",
    navMoviesBtn: "फिल्में",
    navNewAndPopularBtn: "नया और लोकप्रिय",
    navMyListBtn: "मेरी सूची",
    playBtn: "चलाएं",
    moreInfoBtn: "अधिक जानकारी",
    trending: "प्रचलित",
    nowPlaying: "अब चल रही हैं",
    popular: "लोकप्रिय",
    topRated: "सर्वोच्च रेटेड",
    upcoming: "आगामी",
    profileSettings: "प्रोफ़ाइल सेटिंग्स",
  },
  marathi: {
    search: "शोध",
    gptSearchPlaceholder: "काय पहावे याची खात्री नाही? येथे प्रारंभ करा. . .",
    logout: "लॉगआउट करा",
    gptSearchBtnPlaceholder: "GPT सह एक्सप्लोर करा",
    navHomeBtn: "होम",
    navTvShowBtn: "टीव्ही शो",
    navMoviesBtn: "चित्रपट",
    navNewAndPopularBtn: "नवीन आणि लोकप्रिय",
    navMyListBtn: "माझी यादी",
    playBtn: "प्ले",
    moreInfoBtn: "अधिक माहिती",
    trending: "ट्रेंडिंग",
    nowPlaying: "आता प्ले होत आहे",
    popular: "लोकप्रिय",
    topRated: "उच्च रेट केलेले",
    upcoming: "उपलब्ध होणार",
    profileSettings: "प्रोफाइल सेटिंग्ज",
  },
  tamil: {
    search: "தேடு",
    gptSearchPlaceholder:
      "என்ன பார்க்க வேண்டும் என தெரியவில்லை? இங்கு தொடங்கவும்...",
    logout: "வெளியேறு",
    gptSearchBtnPlaceholder: "GPT மூலம் ஆராயுங்கள்",
    navHomeBtn: "முகப்பு",
    navTvShowBtn: "டிவி ஷோ",
    navMoviesBtn: "திரைப்படங்கள்",
    navNewAndPopularBtn: "புதிய மற்றும் பிரபலமான",
    navMyListBtn: "என் பட்டியல்",
    playBtn: "ஒலியுங்கள்",
    moreInfoBtn: "மேலும் தகவல்",
    trending: "பிரபலமானது",
    nowPlaying: "இப்போது ஒலிக்கிறது",
    popular: "பிரபலமான",
    topRated: "உயர் மதிப்பீடு",
    upcoming: "வந்துவிடுகிறது",
    profileSettings: "சுயவிவரம் அமைப்புகள்",
  },
  telugu: {
    search: "సోండించు",
    gptSearchPlaceholder: "ఏది చూడాలో తెలుసుకోవడం లేదు? ఇక్కడ ప్రారంభించండి...",
    logout: "లాగ్ అవుట్",
    gptSearchBtnPlaceholder: "GPT తో అన్వేషించండి",
    navHomeBtn: "హోమ్",
    navTvShowBtn: "టీవీ షోలు",
    navMoviesBtn: "చిత్రాలు",
    navNewAndPopularBtn: "కొత్త మరియు ప్రజాదరణ పొందిన",
    navMyListBtn: "నా జాబితా",
    playBtn: "ప్లే",
    moreInfoBtn: "ఇంకా సమాచారం",
    trending: "ట్రెండింగ్",
    nowPlaying: "ప్రస్తుతం ప్రదర్శిస్తున్నారు",
    popular: "ప్రజాదరణ పొందిన",
    topRated: "ఉన్నత రేటింగ్",
    upcoming: "రాబోయే",
    profileSettings: "ప్రొఫైల్ సెట్టింగ్స్",
  },
  spanish: {
    search: "Buscar",
    gptSearchPlaceholder: "¿No estás seguro de qué ver? Comienza aquí...",
    logout: "Cerrar sesión",
    gptSearchBtnPlaceholder: "Explora con GPT",
    navHomeBtn: "Inicio",
    navTvShowBtn: "Series",
    navMoviesBtn: "Películas",
    navNewAndPopularBtn: "Nuevas y populares",
    navMyListBtn: "Mi lista",
    playBtn: "Reproducir",
    moreInfoBtn: "Más información",
    trending: "Tendencias",
    nowPlaying: "Ahora en reproducción",
    popular: "Popular",
    topRated: "Mejor valoradas",
    upcoming: "Próximamente",
    profileSettings: "Configuración del perfil",
  },
  korean: {
    search: "검색",
    gptSearchPlaceholder: "무엇을 볼지 모르겠나요? 여기서 시작하세요...",
    logout: "로그아웃",
    gptSearchBtnPlaceholder: "GPT와 탐색하기",
    navHomeBtn: "홈",
    navTvShowBtn: "TV 프로그램",
    navMoviesBtn: "영화",
    navNewAndPopularBtn: "새로운 및 인기",
    navMyListBtn: "내 목록",
    playBtn: "재생",
    moreInfoBtn: "자세히 보기",
    trending: "트렌드",
    nowPlaying: "현재 재생 중",
    popular: "인기",
    topRated: "최고 평점",
    upcoming: "곧 출시 예정",
    profileSettings: "프로필 설정",
  },
  japanese: {
    search: "検索",
    gptSearchPlaceholder:
      "何を見るか決まっていませんか？ここから始めましょう...",
    logout: "ログアウト",
    gptSearchBtnPlaceholder: "GPTで探す",
    navHomeBtn: "ホーム",
    navTvShowBtn: "テレビ番組",
    navMoviesBtn: "映画",
    navNewAndPopularBtn: "新着・人気",
    navMyListBtn: "マイリスト",
    playBtn: "再生",
    moreInfoBtn: "詳細情報",
    trending: "トレンド",
    nowPlaying: "現在再生中",
    popular: "人気",
    topRated: "高評価",
    upcoming: "近日公開",
    profileSettings: "プロフィール設定",
  },
};
